### ISSUE TITLE
Allow to choose which IP to announce

### ISSUE THREAD

**Issue by brechtcs** [mafintosh/dotlocal#2]
Using the avahi CLI, you can choose to publish a .local domain for any IP address, for example: `avahi-publish -a -R example.local 10.0.1.4`. It might be useful to support that behaviour here too.

Let me know if you're interested, then I can draw up a PR.

**Comment by mafintosh** [comment]
When I wrote it, I wanted to add that but thought "This would be a great PR". Please send one :)

**Comment by mafintosh** [comment]
Fixed by you in 1.1.0
